global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnitsNetsIssue.DataContracts;
global using UnitsNetsIssue.DataContracts.Serialization;
global using UnitsNetsIssue.Models;
global using UnitsNetsIssue.Presentation;
global using UnitsNetsIssue.Services.Caching;
global using UnitsNetsIssue.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
